/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
  const ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
  const ElLoadingDirective: typeof import('element-plus/es')['ElLoadingDirective']
  const ElLoadingService: typeof import('element-plus/es')['ElLoadingService']
  const ElOption: typeof import('element-plus/es')['ElOption']
}
