/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCascaderMenu: typeof import('element-plus/es')['ElCascaderMenu']
    ElCascaderNode: typeof import('element-plus/es')['ElCascaderNode']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCollapseTransition: typeof import('element-plus/es')['ElCollapseTransition']
    ElDropdownCollection: typeof import('element-plus/es')['ElDropdownCollection']
    ElDropdownCollectionItem: typeof import('element-plus/es')['ElDropdownCollectionItem']
    ElDropdownItemImpl: typeof import('element-plus/es')['ElDropdownItemImpl']
    ElFocusGroupCollection: typeof import('element-plus/es')['ElFocusGroupCollection']
    ElFocusTrap: typeof import('element-plus/es')['ElFocusTrap']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOnlyChild: typeof import('element-plus/es')['ElOnlyChild']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElOptions: typeof import('element-plus/es')['ElOptions']
    ElOverlay: typeof import('element-plus/es')['ElOverlay']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRovingFocusCollectionItem: typeof import('element-plus/es')['ElRovingFocusCollectionItem']
    ElRovingFocusGroup: typeof import('element-plus/es')['ElRovingFocusGroup']
    ElRovingFocusGroupImpl: typeof import('element-plus/es')['ElRovingFocusGroupImpl']
    ElRovingFocusItem: typeof import('element-plus/es')['ElRovingFocusItem']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelectMenu: typeof import('element-plus/es')['ElSelectMenu']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElTreeNode: typeof import('element-plus/es')['ElTreeNode']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
